export const TWEETS_GET = 'TWEETS_GET';
export const TWEETS_GET_SUCCESS = 'TWEETS_GET_SUCCESS';
export const TWEETS_GET_FAIL = 'TWEETS_GET_FAIL';
export const COUNT_UPDATE = 'COUNT_UPDATE';
export const SORT_UPDATE = 'SORT_UPDATE';

